#此文件包含所有能配置的属性，只用来查看使用，程序使用的是config.yml中的配置
configs:

    #规则是否生效,true或者false，默认为true
  - enable: true
    #类型，forward或http或sock5,表示端口转发或http代理或sock5代理，默认为forward
    serverType: forward
    #本地监听的端口号
    serverPort: 13306
    #转发的目标IP，serverType为forward时此参数才有意义
    remoteHost: 127.0.0.1
    #转发的目标端口，serverType为forward时此参数才有意义
    remotePort: 3306
    #是否需要认证，serverType为http和sock5时此参数才有意义
    needLogin: true
    #认证账号，serverType为http和sock5时此参数才有意义
    username: "user"
    #认证密码，serverType为http和sock5时此参数才有意义
    password: "pwd"
    #是否需要通过后端代理连接远程服务器，会覆盖全局的配置
    proxyNeed: false
    #如果需要后端口代理，代理连接类型，http或socks5，会覆盖全局的配置
    proxyType: http
    #如果需要后端口代理，代理连接IP，会覆盖全局的配置
    proxyIp: 127.0.0.1
    #如果需要后端口代理，代理连接Port，会覆盖全局的配置
    proxyPort: 1080
    #如果需要后端口代理，代理连接用户名,为空说明不需要认证，会覆盖全局的配置
    proxyUsername: "proxyUser"
    #如果需要后端口代理，代理连接密码,为空说明不需要认证，会覆盖全局的配置
    proxyPassword: "proxyPwd"

#===后端代理全局配置，会对所有的configs有效，以下配置都有默认值，如果没配置，则采用默认===#
global:
  #是否需要通过后端代理连接远程服务器
  proxyNeed: false
  #代理连接类型，http或socks5
  proxyType: http
  #代理连接IP
  proxyIp: 127.0.0.1
  #代理连接Port
  proxyPort: 1080
  #代理连接用户名,为空说明不需要认证
  proxyUsername: ""
  #代理连接密码,为空说明不需要认证
  proxyPassword: ""